-- TEMPORARY TABLE 
-- TEMPORARY TABLE IS NOT A ACTUAL TABLE IT'S ONLY VISIBLE IN TIME THAT IT CREATED 
-- AFTER CREATING TEMP TABLE IF WE SHUT OUR SYSTM IN LOG IN AFTER FEW MINUTE TEMP TABLE WILL BE GONE 

-- TWO WAY TO CREATED A TEMPORARY TABLE 
-- HERE IS FIRST ONE 
 CREATE TABLE TEMP_TABLE 
( ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL ,
  AGE INT NOT NULL );
  -- IT SUCCESSFUL CREATED 
  
  SELECT * FROM TEMP_TABLE ;
  
  -- IF WE REFRESH THE TABLE IT NOT THERE BECAUSE IT JUST A TEMP TABLE 
  
  -- NOW INSERTING DATA IN TO IT 
  INSERT INTO TEMP_TABLE(ID,NAME,AGE) VALUES
  (1,'ROHIT',18),
  (2,'RAMAN',20),
  (3,'AMIT',33);
  
-- NOW WE HAVE INSERT IN AND CHECK OUR DATA
  SELECT * FROM TEMP_TABLE ;
  
  -- SECOND WAY IS MUCH FASTER THAN FIRST ONE \
  -- BUILD IT BY INSERTING DATA 
  
  CREATE TEMPORARY TABLE EMP_BASIC_INFO 
  SELECT First_Name,Last_Name,Age,Gender
  FROM employee ;
  
  -- IF WE RUN I WE WILL GET OUR OUTPUT
  SELECT * FROM EMP_BASIC_INFO;

-- IT IS BEST AND MOST USUABLE WAY TO CREATE TEMPORARY TABLE