-- STORED PROCEDURES 
-- FIRST JUSTT WRITE SIMPLE REGULAR QUIRY

SELECT * FROM startersql.employee
WHERE Gender='Female';

-- NOW PUT IT IN TO STORED PROCEDURES
CREATE PROCEDURE FEMALE_INFO ()
SELECT * FROM startersql.employee
WHERE Gender='Female';
-- WE RUN THIS AND IT JUST CREATE A STORED PROCEDURE
-- WE CAN CLICK REFRESH AND SEE IT THERE 

-- IF WE WANT TO CALL IT AND USE IT WE CAN CALL IT BY WRITING :
CALL FEMALE_INFO();


-- BEST PRACTICE TO USE A DELIMITER AND A BEGIN AND END TO REALLY CONTROL WHAT IN THE STORED PROCEDURES
-- LET SEE HOW CAN WE DO THIS 
-- WE CAN USE // OR $$ FOR DELIMITER 

-- WHEN WE CHANGE THIS DELIMITER IT NOW READS IN EVERY THING 
DELIMITER $$
CREATE PROCEDURE SALARY_1()
BEGIN 
     SELECT * FROM employee
     WHERE Salary >35000;
     SELECT * FROM employee
     WHERE Salary>40000;
END $$
-- NOW WE HAVE CHANGE THE DELIMITER BACK AFTER TO MAKE IT DEFAULT AGAIN
DELIMITER ;
CALL SALARY_1();

-- WE CAN DROP IT BY USING THIS 
DROP PROCEDURE SALARY_1;


-- WE CAN ALSO ADD PARAMETER 
DELIMITER $$ 
CREATE PROCEDURE SALARY_2(EMP_ID INT)
BEGIN
     SELECT * FROM employee
     WHERE Salary >35000;
     SELECT * FROM employee
     WHERE Salary>40000;
END $$

DELIMITER ;

CALL SALARY_2(1);

     