# WHERE CLAUSE-
-- IT USED FOR JUST TO FILTER RECORS 
-- IF WE SAY THAT " Salray >50000 THEN ONLY ROWS WHERE Salary IS Greater THAN 50000 WILL RETURN

# SO LETS LOOK AT HOW THIS WORK

SELECT *
FROM startersql.employee
WHERE Salary > 50000;

SELECT * 
FROM employee
WHERE Salary >= 50000 ;

SELECT * 
FROM employee
WHERE Gender='Female' ;


-- WE CAN ALSO USE IT FOR NOT " Female OR ANY THING " 
SELECT *
FROM employee
WHERE Gender !='Female';

-- WE CAN USE WHERE IN DATE values
SELECT * 
FROM employee
WHERE Join_Date > 01-01-2022 ;

-- LIKE STATEMENT

-- THERE ARE SPEACIAL CHARACTERS "a% AND a_"

-- A% MEAN FIRST LETTER WILL BE "A" AND ANY THING AFTER THAT 
SELECT * 
FROM employee
WHERE First_Name LIKE 'A%';

-- %A MEAN END WITH "A" AND ANYTHING BEFORE THAT 
SELECT * 
FROM employee
WHERE First_Name LIKE '%A';

-- %A% MEAN ANYTHING BEFOR IT AND ANYTHING AFTER THAT BUT ATLEAST CONTAIN "A"


-- MEAN A SPECIFIC VALUE
SELECT * 
FROM employee
WHERE First_Name LIKE 'A__%';

SELECT * 
FROM employee
WHERE First_Name LIKE 'A__%';