-- HAVING VS WHERE 
-- BOTH ARE CRAETED TO FILTER DATA BUT THEY BOTH FILTER DIFFERENT THINGS
-- WHERE IS GOES FOR FILTER ROWS BASED COLUMN DATA 
-- HAVING IS GOES TO FILTER ROWS BASED AGGREGATE COLUMN DATA WHEN GROUPED

SELECT Gender,AVG(Age)
FROM startersql.employee
GROUP BY Gender
;



SELECT Gender,AVG(Age)
FROM startersql.employee
WHERE AVG(Age) > 40
GROUP BY Gender
;
-- IT'S NOT WORK ON THE SYNTAX WHERE COMES BEFORE TH GROUP BY SO IT'S CANT FILTER

-- LET'S TRY WITH HAVING
 SELECT Gender,AVG(Age)
FROM startersql.employee
GROUP BY Gender
HAVING AVG(Age) > 32.5
;

SELECT Gender,AVG(Age) AS AVG_AGE
FROM startersql.employee
GROUP BY Gender
HAVING AVG_AGE > 32.5
;
