-- SELECT STATEMENT 
-- WE WILL DISCUSE IT IN THIS SERIES 
-- IT WILL SELECT EVERY THING IN THAT TABLE "employee"
SELECT 
    *
FROM startersql.employee;

-- LET SELECT SPECIFIC COLUMNS
SELECT First_Name FROM EMPLOYEE ;

-- NOW LET ADD MORE COLUMN AS SPECIFIC COLUMNS
SELECT First_Name,Last_Name FROM EMPLOYEE ;

-- RIGHT FORMATE DOES NOT MATTER WHEN SELECTING DATA 
SELECT First_Name,Last_Name,Age,Salary FROM EMPLOYEE ;

-- SQL RIGHT FORMATE TO ARRANGE QUIRY LIKE THAT
SELECT 
    First_Name, Last_Name, Age, Salary
FROM
    EMPLOYEE;
    
-- LETS ADD SOME CALCULATION IN 
SELECT First_Name,
Age+10,
Salary+10000
FROM Employee ;
-- YOU CAN SEE THE RESULT BEFORE SELECT QUIRY AND THIS QUIRY IT HAS ADDED 10 MORE IN AGE AND 10000 IN SALARY

-- YOU ALL HAS A QUESTION NOW TELL ME THE OUTPUT OF THIS QUIRY
SELECT First_Name,
Age+10,
(Salary+10000)*100
FROM Employee ;

-- NOW I CAN LOOK AT FIRST_NAME HERE ARE MANY DUPLICATE FIRST_NAME 
SELECT First_Name FROM employee ;

SELECT DISTINCT First_Name FROM employee ;
-- THIS QUIRY WILL IGNORE ALL DUPLICATE NAME ONLY WILL SHOW YOU UNIQU NAME