-- CREATE A NEW DATABASE  BY USING THIS SIMPLE QUIRY
CREATE DATABASE sqlmaster;


-- WE ALSO DO IT BY MANUAL BY TAPPING TWO TIME ON DATABASE NAME LIST SHOW UN LEFT SIDE
USE sqlmaster;
-- IT'S SELECT THE DATABASE 

-- NOW WE ARE GOING TO CREATE A TBALE TO STORE DATA 
CREATE TABLE beginner( Id INT NOT NULL AUTO_INCREMENT,
fname VARCHAR(100)NOT NULL,
lname VARCHAR(100) NOT NULL,
age INT NOT NULL,
gender VARCHAR(20),
PRIMARY KEY(Id)
);
-- HERE IN BRACKETS THOSE ARE ARE IN BLACK ARE COLUMNS OTHER ARE DATA TYPE AND CONSTRAINT 


-- ADDING SINGLE-SINGLE DATA IN TO TABLE 
INSERT INTO 
beginner VALUES(
1,'ARMAN','SINGH',26,'MALE');

-- ADDING MULTIPLE DATA IN TO TABLE 
INSERT INTO beginner(id,fname,lname,age,gender) VALUES 
(2,'VIRAT','KOHLI',36,'MALE'),
(3,'ROHIT','SHARMA',45, 'MALE'),
(4,'SMRITI','MANDHANA',29,'FEMALE');
-- WE CAN DO BOTH OF THEM

-- HERE WE SEE OUR INSERTED DATA 
SELECT * 
FROM beginner;