-- LIMIT AND ALIASING 
-- LIMIT IS JUST  HOW MANY ROWS YOU WANT IN YOUR OUTPUT 

SELECT * 
FROM startersql.employee
LIMIT 5;

-- IF WE CHANGE SOME THING LIKE ORDER OR GROUP BY IT WILL CHANGE THE OUTPUT 
SELECT * 
FROM startersql.employee
ORDER BY AGE DESC
LIMIT 5;

-- NOW THERE IS AN ADDITIONAL PARAMATER WHICH WE CAN ACCESS USING COMMA AFTER LIMIT TO FIND SPECIFIES VALUES
SELECT * 
FROM startersql.employee
;

SELECT * 
FROM startersql.employee
LIMIT 5,3;
-- IT MEAN START FROM 5 AND END WHEN TAKE 3 ROWS 
# EXAMPLE IF ROWS ARE LIKE 1,2,.....10 THEN IT WILL RETURN 6,7,8 IT WILL IGNORE 1,2,...5

-- YOU CAN USE IT IN CASE OF FINDING 2ND, 3RD,4TH LARGEST SALARY OR AGE 
SELECT * 
FROM startersql.employee
ORDER BY SALARY DESC
LIMIT 2,1;
# THIRD HIGHEST SALARY

-- ALIASING
-- IT JUST A WAY TO CHANGE NAME OF COLUMN OR A NEW CALCULATION COLUMN 

SELECT Gender,AVG(Age) 
FROM startersql.employee
GROUP BY Gender;

-- TO USE ALIAS USE KEYWORD "AS" 
SELECT Gender,AVG(Age) AS AVG_AGE 
FROM startersql.employee
GROUP BY Gender;




