-- CASE STATEMENTS

-- CASE STATEMENT IS LIKE PROGRAMMING LANGUAGE IF-ELSE OR EXCEL IF-ELSE FORMULA
SELECT * 
FROM startersql.employee;

SELECT Age,
CASE 
    WHEN Age<=30 THEN 'YOUNG'
    WHEN Age BETWEEN 31 AND 45 THEN 'OLD'
    WHEN Age >=46 THEN 'DEATH ON DOOR'
END AS LABEL
FROM employee;

-- QUESTION:- IF SALARY IS EQUAL OR LESS THAN 45000 WHEN BONUS WILL BE 5% AND IF SALARY IS GREATER THAN 45000 BONUS WILL BE 10%
-- IF YOU WORK AT IT DEPT THEN IT WILL BE 15% BONUS
SELECT Salary,Department_Region ,
CASE 
    WHEN Salary <=45000 THEN ROUND(Salary*0.5,2)
    WHEN Salary >45000 THEN ROUND(Salary*0.10,2)
    WHEN Department_Region ='IT' THEN ROUND(Salary*0.15,2)
END AS BONUS 
FROM employee;    

