-- JOIN 
-- JOIN ALOW TO COMBINE TWO TABLE TOGETHER WHEN WE HAVE ONE COMMON COLUMN 
-- THERE ARE MANY TYPE OF JOIN I AM JOIN TO EXPLAIN ALL OF THE BELOW


-- FIRST TABLE IS CUSTOMERS AND SECOND IS OREDRS
SELECT * 
FROM startersql.customers;

SELECT *
FROM startersql.orders;

-- LET'S START WITH INEER JOIN 
-- INNER JOIN:-IT WILL RETURN ROWS THAT ARE SAME IN BOTH COLUMN
SELECT c.CustName,o.Product FROM customers c
LEFT JOIN orders o ON c.CustID=o.CustID ;
-- IF CUSTID IS NULL IN ORDERS TABLE IT WILL SHOWN IN RESULT 


-- NOW IT'S TIME FOR THE OUTER JOINS
--  OUTER JOIN HAVE TWO TYPE LEFT JOIN AND RIGHT JOIN 
-- LEFT JOIN:- IT WILL RETURN ALL FROM THE LEFT TABLE EVEN IF THERE IS NO MATCH IN JOIN 

SELECT c.CustName,o.Product FROM orders o
LEFT JOIN customers c ON o.CustID = c.CustID;
-- IN RESULT CUSTNAME HAS A NULL VALUE SHOW IT'S SHOWN IN RESULT 

-- LET'S CHECK OUT THE RIGHT JOIN I
-- IT'S JUST OPPOSITE TO THE LEFT JOIN 
SELECT c.CustName,o.Product FROM orders o
RIGHT JOIN customers c ON o.CustID = c.CustID;


-- SELF JOIN 
-- A SELF JOIN IS WHERE YOU TIE A TABLE TI ITSELF

SELECT * FROM employee;

SELECT * FROM employee E1
JOIN employee E2 ON E1.emp_id=E2.emp_id;

SELECT *
FROM employee E1
JOIN employee E2 
ON E1.emp_id  = E2.emp_id
;


-- JOINING MULTIPLE TABLE 

-- WE HAVE THREE TABLE
SELECT * FROM pizzas 
JOIN  order_details ON pizzas.pizza_id=order_details.pizza_id
LEFT JOIN orders ON orders.order_id=order_details.order_id





