-- Let's TAKE A LOOK AT STRING FUNCTIONS
 
-- LENGTH()
-- IT WILL RETURN LENGTH OF STRING 
SELECT LENGTH('INDIA   ');
-- IT RETURN 8 ,THE REASON IS IT WILL ALSO COUNT THE SPACES AS LENGTH

SELECT First_Name,LENGTH(First_Name) 
FROM employee;


-- UPPER() 
-- IT WILL TURN STRING IN TO UPPER CASE
SELECT UPPER('india');

SELECT First_Name , UPPER(First_Name)
FROM employee;

-- LOWER()
-- IT WILL CHANGE ALL THE STRING IN TO LOWER CASE
SELECT LOWER('INDIA');

SELECT Last_Name,LOWER(Last_Name) FROM employee;

-- TRIM()
SELECT TRIM('INDI'      'A'        );

-- LTRIM()
SELECT LTRIM('   I AM FROM     INDIA');
-- IT WILL TRIM ALL SPACE FROM LEFT SIDE

-- RTRIM
SELECT RTRIM('I AM FROM         INDIA');
-- IT WILL TRIM ALL SACES FROM RIGHT SIDE 


-- LEFT()
SELECT LEFT('INDIA',2);

SELECT Gender,LEFT(Gender,1) FROM employee;
-- IT ALLOW US TO TAKE A CERTAIN AMOUNT OF STRING FROM THE LEFT SIDE

-- RIGHT()
SELECT Join_Date , RIGHT(Join_Date,4) AS YEAR FROM employee;
-- IT ALLOW US TO TAKE A CERTAIN AMOUNT OF STRING FROM THE RIGHT 

-- SUBSTRING()  ----IMPORTANT---
-- BY USING IT WE CAN TAKE CHARACTERS FROM ANYWHERE IN THE STRING
SELECT SUBSTRING('SQL MY LANGUAGE',1,6);

-- WE CAN ACCESS ANY THING LIKE DATE,MONTH,YEAR 
SELECT Join_Date,SUBSTRING(Join_Date,1,2) AS DAY FROM employee;  -- DAY
SELECT Join_Date,SUBSTRING(Join_Date,4,2) AS MONTH FROM employee; -- MONTH
SELECT Join_Date,SUBSTRING(Join_Date,7,4) FROM employee; -- YEAR


-- REPLACE()
-- IT'S REPLACE THE EXITING VALUE BY NEW VALUE
SELECT REPLACE('INDIAN','N','') ;

-- LOCATE()
-- IT RETURN  THE LOCATION OF SEARCHING STRING FROM THE EXITING ONE 
SELECT LOCATE('D','INDIAN');

SELECT First_Name,LOCATE('A',First_Name) FROM employee;


-- CONCAT()
-- IT CONNECT TOGETHER TWO STRING IN TO ONE 
SELECT CONCAT('IND','IAN');

SELECT CONCAT(First_Name,' ',Last_Name) FROM employee;


