-- WINDOW FUNCTION

-- WINDOW FUNCTION ARE REALLY POWERFUL , LIKE SOMEWHERE GROUP BY  EXPECT THEY DON'T ROLL EVERYTHING UPTO I ROW
-- WE WILL LOOK AT ROW_NUMBER,RANK(),DENSE_RANK()
SELECT * FROM startersql.employee;

-- IT'S GROUP BY 
SELECT Gender,MAX(Salary) FROM employee
GROUP BY Gender;

-- LET DO AT WINDOW FN
SELECT Gender,AVG(Salary)  OVER(partition by Gender ORDER BY Salary DESC) FROM employee
;

-- NOW USE RANK(),DENSE_RANK(),AND ROW_NUMBER()
SELECT First_Name,Last_Name,Gender,Salary,
ROW_NUMBER() OVER(PARTITION BY Gender ORDER BY Salary DESC) 
FROM employee;

-- NOW COMPARE WITH RANK()
SELECT First_Name,Last_Name,Gender,Salary,
ROW_NUMBER() OVER(PARTITION BY Gender) AS ROW_NUM,
RANK()  OVER(PARTITION BY Gender ORDER BY Salary DESC) AS RANK_NUM
FROM employee ;

-- LET DO SAME WITH DENSE_RANK
SELECT First_Name,Last_Name,Gender,Salary,
ROW_NUMBER() OVER(PARTITION BY Gender) AS ROW_NUM,
RANK()  OVER(PARTITION BY Gender ORDER BY Salary DESC) AS RANK_NUM,
DENSE_RANK() OVER(PARTITION BY Gender ORDER BY Salary DESC) AS DENSE_NUM
FROM employee
 
 


