SELECT *
FROM dirty;

-- FINDING DUPLICATE
-- LET'S FIND DUPLICATE 
WITH DUPLICATE1 AS (
SELECT *, ROW_NUMBER() OVER(PARTITION BY incident_id,crime_type,latitude,longitude ) AS ROW_NUM 
FROM dirty )
SELECT * 
FROM DUPLICATE1
WHERE ROW_NUM >1
;  
-- WE RUN THIS QUIRY AND FIND ALL DUPLICATES 

-- LET'S VERIFY THE DUPLICATE THAT THESE ARE ACTUAL DUPLICATE OR NOT
SELECT * FROM dirty
WHERE incident_id='INC000263';

-- WE CHECK THOSE VALUE'INC000008' ,'INC000264','INC000109','INC000263' AND FIND YES THESE ARE TWO TIME IN OUR DATA
-- SO THESE ARE DUPLICATE

-- DELETING DUPLICATE()
-- NOW WE ARE GOING TO REMOVING ALL OF THOSE DUPLICATE

WITH DUPLICATE1 AS (
SELECT *, ROW_NUMBER() OVER(PARTITION BY incident_id,crime_type,latitude,longitude ) AS ROW_NUM 
FROM dirty )
DELETE
FROM DUPLICATE1
WHERE ROW_NUM >1
;
-- SEE HERE  WE CAN'T DIRECT DELETE DATA FROM CTE TABLE SO WE HAVE TO MAKE A ANOTHER TABLE LOOK LIKE EXITING ONE 
-- AND I HAVE TO CREATE ANOTHER COLUMN FOR ROW_NUM() 
-- LET'S DO THIS
 
 -- WE HAVE CREATE A TABLESAME AS dirty
 CREATE TABLE stage_01
 LIKE dirty;

SELECT * 
FROM stage_01;
-- IT'S WORK  

-- NOW CREATING A NEW COLUMN ROW_NUM 

ALTER TABLE stage_01
ADD COLUMN row_num INT 
;

-- WE HAVE CHECK COLUMN IT HAVE BEEN ADDED SUCCESSFULLY
SELECT * 
FROM stage_01;

-- NOW INSERTING THE DATA IN TO stage_01
INSERT INTO stage_01 
SELECT *, ROW_NUMBER() OVER(PARTITION BY incident_id,crime_type,latitude,longitude ) AS ROW_NUM 
FROM dirty ;

SELECT * 
FROM stage_01;

-- NOW IN NEW TABLE JUST CHECK DUPLICATE IN DATA 
SELECT *
FROM stage_01 
WHERE row_num >1;
-- WHEN WE RUN THIS 182 ROWS EFECTED
-- NOW HERE SAME DUPLICATE VALUE 
-- BUT WE CAN DELETE HERE DUPLICATE AND OUR UNIQUE DATA SAFE 
-- AND MAIN DATA WILL(dirty TABLE) BE SAME AS WE IMPORTED BECAUSE IF WE DO SOMETHING WRONG WE CAN USE IT AGAIN 

-- LET DELETE DUPLICATE
SET SQL_SAFE_UPDATES=0;

DELETE 
FROM stage_01 
WHERE row_num >1;
-- WE RUN THIS SAME 182 ROWS DELETED 
SELECT *
FROM stage_01 
WHERE row_num >1;


SELECT *
FROM stage_01 
WHERE crime_type = 0
;

--  NOW JUST STANDERIZE THE DATA
SELECT * 
FROM stage_01;

SELECT TRIM(district) 
FROM stage_01;
SELECT UPPER(LEFT(crime_type,1)) 
FROM stage_01;

-- IN crime_type COLUMN THERE SO MANY LOWER AND UPPER CASE SO PULL THIS MOVE
UPDATE stage_01
SET district=LOWER(district) ;


UPDATE stage_01
SET district=TRIM(district) ;


-- SELECT LENGTH(district) FROM stage_01 ORDER BY LENGTH(district) DESC;
SELECT SUBSTRING(district,2,9) 
FROM stage_01;
SELECT CONCAT(UPPER(LEFT(district,1)),SUBSTRING(district,2,9)) , district 
FROM stage_01;

-- NOW WE ARE GOING TO CORRECT STRUCTURE OF DISTRICT COLUMN
UPDATE stage_01
SET district=CONCAT(UPPER(LEFT(district,1)),SUBSTRING(district,2,9));



